### ISSUE TITLE
📝 docs: Document Data Description Content

### ISSUE THREAD

**Issue by Daehyun-Bigbread** [Kakaotech-18-Ecommerce/Kakaotech-18-AI#25]
# Title

- 데이터 작업 내용 및 변수 & ERD 내용 정리 문서화

# TODO

- [ ] 데이터 변수 설명
- [ ] EDA 내용 설명 - Feature Importance 등등
- [ ] ERD 내용 설명 - BE & Cloud랑 얘기 해봐야함.

# etc

- 데이터 작업 내용 및 변수 & ERD 내용 정리 문서화가 필요하다고 해서 이슈는 생성해 놓았습니다. 이건 저희 Task 다 끝나고 발표 준비할때 해도 될거 같아요!
