### ISSUE TITLE
🐛 fix: predicted_review_star issue

### ISSUE THREAD

**Issue by Daehyun-Bigbread** [Kakaotech-18-Ecommerce/Kakaotech-18-AI#42]
# Title

- predicted_review_star

# TODO

- [x] 수정된 데이터를 기반으로 해서 predicted_review_star 값 낮게 나오는 문제 해결
- [x] model_training_and_prediction.py feature 별 weight 값 수정
- [x] research file 수정 (ipynb 파일 전부 다)

# etc

- predicted_review_star 값이 생각보다 4점대를 다 넘지 않습니다. 이건 문제가 있다고 보고 고쳐야 할거 같습니다.
