### ISSUE TITLE
✨ feat: Create test scripts and run tests

### ISSUE THREAD

**Issue by Daehyun-Bigbread** [Kakaotech-18-Ecommerce/Kakaotech-18-AI#52]
# Title

- 테스트 스크립트 작성 및 테스트 실행

# TODO

- [ ] pytest 기반 테스트 케이스 작성 (tests/ 디렉토리 생성)
- [ ] 각 기능에 대한 유닛 테스트 작성
- [ ] 테스트 실행 및 디버깅

# etc

- 검색 엔진 기능을 테스트하기 위한 테스트 케이스를 작성하고, 테스트를 수행
